package problem01to10;

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Problem2 {
	
	int temp;
	
	public int run(int oneBack, int num, int result){
		if(num>4000000){
			System.out.println(result);
			return result;
		}else{
			if(num % 2 == 0){
				result = result + num;
			}
			temp = num;
			num = num + oneBack;
			oneBack = temp;
			run(oneBack, num, result);
		}
		return result;
	}
}
